services:
  postgres:
    container_name: postgres
    environment:
      PGDATA: /home/ahmad/postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin 
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres:/home/ahmad/postgres
volumes:
  postgres:

